### ISSUE TITLE
NPE

### ISSUE THREAD

**Issue by ServeMe** [deano2390/MaterialShowcaseView#121]
my users receive NPE when use this library
after checking the environment this exception happened when user try to do a slide touch on android 3.2
this is the stack for the error
java.lang.NullPointerException
	at uk.co.deanwild.materialshowcaseview.MaterialShowcaseView.fadeOut(MaterialShowcaseView.java:799)
	at uk.co.deanwild.materialshowcaseview.MaterialShowcaseView.hide(MaterialShowcaseView.java:777)
	at uk.co.deanwild.materialshowcaseview.MaterialShowcaseView.onTouch(MaterialShowcaseView.java:206)
	at android.view.View.dispatchTouchEvent(View.java:4636)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:1554)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1320)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:1560)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1333)
	at com.android.internal.policy.impl.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:1881)
	at com.android.internal.policy.impl.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1296)
	at android.app.Activity.dispatchTouchEvent(Activity.java:2315)
	at android.support.v7.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:71)
	at android.support.v7.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:71)
	at com.android.internal.policy.impl.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:1854)
	at android.view.View.dispatchPointerEvent(View.java:4708)
	at android.view.ViewRoot.deliverPointerEvent(ViewRoot.java:2448)
	at android.view.ViewRoot.handleMessage(ViewRoot.java:2109)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:132)
	at android.app.ActivityThread.main(ActivityThread.java:4123)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:491)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:844)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:602)
	at dalvik.system.NativeStart.main(Native Method)

**Comment by cyber7eyes** [comment]
@ServeMe I fixed it and pull request from my repo 
https://github.com/cyber7eyes/MaterialShowcaseView

**Comment by noordawod** [comment]
I think this project has no maintainer, sadly.

**Comment by ServeMe** [comment]
@cyber7eyes how can I use this I tried to add it on gradle but it looks like it is the same with original
