### ISSUE TITLE
App Crash In click event.

### ISSUE THREAD

**Issue by kashyapbakori** [deano2390/MaterialShowcaseView#152]
FATAL EXCEPTION: main
                                                   Process: com.s4devteam.TextOnPhoto, PID: 11510
                                                   java.lang.IllegalStateException: Cannot start this animator on a detached view!
                                                       at android.view.RenderNode.addAnimator(RenderNode.java:786)
                                                       at android.view.RenderNodeAnimator.setTarget(RenderNodeAnimator.java:300)
                                                       at android.view.RenderNodeAnimator.setTarget(RenderNodeAnimator.java:282)
                                                       at android.animation.RevealAnimator.<init>(RevealAnimator.java:37)
                                                       at android.view.ViewAnimationUtils.createCircularReveal(ViewAnimationUtils.java:71)
                                                       at uk.co.deanwild.materialshowcaseview.CircularRevealAnimationFactory.animateInView(CircularRevealAnimationFactory.java:29)
                                                       at uk.co.deanwild.materialshowcaseview.MaterialShowcaseView.animateIn(MaterialShowcaseView.java:825)
                                                       at uk.co.deanwild.materialshowcaseview.MaterialShowcaseView$1.run(MaterialShowcaseView.java:794)
                                                       at android.os.Handler.handleCallback(Handler.java:751)
                                                       at android.os.Handler.dispatchMessage(Handler.java:95)
                                                       at android.os.Looper.loop(Looper.java:154)
                                                       at android.app.ActivityThread.main(ActivityThread.java:6123)
                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:867)
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:757)

**Comment by silvafabio** [comment]
Duplicate #145
