### ISSUE TITLE
NullpointerExeption

### ISSUE THREAD

**Issue by frankyxcs** [deano2390/MaterialShowcaseView#69]
Hi 
getting a lot of nullpointerexeptions. for example changing the orientation more or less always this error occures. would be nice  if you can fix this ...

 java.lang.NullPointerException: Attempt to invoke interface method 'java.util.Iterator java.util.List.iterator()' on a null object reference
                                                                                        at uk.co.deanwild.materialshowcaseview.MaterialShowcaseView.notifyOnDisplayed(MaterialShowcaseView.java:208)
                                                                                        at uk.co.deanwild.materialshowcaseview.MaterialShowcaseView.access$1400(MaterialShowcaseView.java:42)
                                                                                        at uk.co.deanwild.materialshowcaseview.MaterialShowcaseView$2.onAnimationStart(MaterialShowcaseView.java:707)
                                                                                        at uk.co.deanwild.materialshowcaseview.AnimationFactory$1.onAnimationStart(AnimationFactory.java:29)
                                                                                        at android.animation.ValueAnimator.notifyStartListeners(ValueAnimator.java:925)
                                                                                        at android.animation.ValueAnimator.start(ValueAnimator.java:962)
                                                                                        at android.animation.ValueAnimator.start(ValueAnimator.java:969)
                                                                                        at android.animation.ObjectAnimator.start(ObjectAnimator.java:829)
                                                                                        at uk.co.deanwild.materialshowcaseview.AnimationFactory.fadeInView(AnimationFactory.java:44)
                                                                                        at uk.co.deanwild.materialshowcaseview.MaterialShowcaseView.fadeIn(MaterialShowcaseView.java:702)
                                                                                        at uk.co.deanwild.materialshowcaseview.MaterialShowcaseView$1.run(MaterialShowcaseView.java:671)
                                                                                        at android.os.Handler.handleCallback(Handler.java:739)
                                                                                        at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                                        at android.os.Looper.loop(Looper.java:145)
                                                                                        at android.app.ActivityThread.main(ActivityThread.java:6117)
                                                                                        at java.lang.reflect.Method.invoke(Native Method)
                                                                                        at java.lang.reflect.Method.invoke(Method.java:372)
                                                                                        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1399)
                                                                                        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1194)

**Comment by jamespizzurro** [comment]
+1

```
java.lang.NullPointerException: Attempt to invoke interface method 'java.util.Iterator java.util.List.iterator()' on a null object reference
	at uk.co.deanwild.materialshowcaseview.MaterialShowcaseView.notifyOnDisplayed(MaterialShowcaseView.java:208)
	at uk.co.deanwild.materialshowcaseview.MaterialShowcaseView.access$1400(MaterialShowcaseView.java:42)
	at uk.co.deanwild.materialshowcaseview.MaterialShowcaseView$2.onAnimationStart(MaterialShowcaseView.java:707)
	at uk.co.deanwild.materialshowcaseview.AnimationFactory$1.onAnimationStart(AnimationFactory.java:29)
	at android.animation.ValueAnimator.notifyStartListeners(ValueAnimator.java:925)
	at android.animation.ValueAnimator.start(ValueAnimator.java:962)
	at android.animation.ValueAnimator.start(ValueAnimator.java:969)
	at android.animation.ObjectAnimator.start(ObjectAnimator.java:829)
	at uk.co.deanwild.materialshowcaseview.AnimationFactory.fadeInView(AnimationFactory.java:44)
	at uk.co.deanwild.materialshowcaseview.MaterialShowcaseView.fadeIn(MaterialShowcaseView.java:702)
	at uk.co.deanwild.materialshowcaseview.MaterialShowcaseView$1.run(MaterialShowcaseView.java:671)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:155)
	at android.app.ActivityThread.main(ActivityThread.java:5696)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1029)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:824)
```

**Comment by ToBoehmK** [comment]
We experienced the same issue in our project.
```java
Fatal Exception: java.lang.NullPointerException: Attempt to invoke interface method 'java.util.Iterator java.util.List.iterator()' on a null object reference
       at uk.co.deanwild.materialshowcaseview.MaterialShowcaseView.notifyOnDisplayed(SourceFile:208)
       at uk.co.deanwild.materialshowcaseview.MaterialShowcaseView.access$1400(SourceFile:42)
       at uk.co.deanwild.materialshowcaseview.MaterialShowcaseView$2.onAnimationStart(SourceFile:707)
       at uk.co.deanwild.materialshowcaseview.AnimationFactory$1.onAnimationStart(SourceFile:29)
       at android.animation.ValueAnimator.notifyStartListeners(ValueAnimator.java:925)
       at android.animation.ValueAnimator.start(ValueAnimator.java:962)
       at android.animation.ValueAnimator.start(ValueAnimator.java:969)
       at android.animation.ObjectAnimator.start(ObjectAnimator.java:829)
       at uk.co.deanwild.materialshowcaseview.AnimationFactory.fadeInView(SourceFile:44)
       at uk.co.deanwild.materialshowcaseview.MaterialShowcaseView.fadeIn(SourceFile:702)
       at uk.co.deanwild.materialshowcaseview.MaterialShowcaseView$1.run(SourceFile:671)
       at android.os.Handler.handleCallback(Handler.java:739)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:135)
       at android.app.ActivityThread.main(ActivityThread.java:5219)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:898)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:693)
```
Is someone already working on that issue?

**Comment by ToBoehmK** [comment]
@frankyxcs @jamespizzurro I have tried to implement a fix. What do you think?

**Comment by frankyxcs** [comment]
hi ToBoemK  ! Cool thanxs will try it out later and tell you !
