### ISSUE TITLE
   java.lang.NoClassDefFoundError: android.support.v7.view.menu.MenuBuilder

### ISSUE THREAD

**Issue by Naqash79** [deano2390/MaterialShowcaseView#72]
Process: uk.co.deanwild.materialshowcaseviewsample, PID: 10187
    java.lang.NoClassDefFoundError: android.support.v7.view.menu.MenuBuilder
            at android.support.v7.app.AppCompatDelegateImplV7.initializePanelMenu(AppCompatDelegateImplV7.java:1194)
            at android.support.v7.app.AppCompatDelegateImplV7.preparePanel(AppCompatDelegateImplV7.java:1258)
            at android.support.v7.app.AppCompatDelegateImplV7.doInvalidatePanelMenu(AppCompatDelegateImplV7.java:1553)
            at android.support.v7.app.AppCompatDelegateImplV7.access$100(AppCompatDelegateImplV7.java:89)
            at android.support.v7.app.AppCompatDelegateImplV7$1.run(AppCompatDelegateImplV7.java:129)
            at android.os.Handler.handleCallback(Handler.java:808)
            at android.os.Handler.dispatchMessage(Handler.java:103)
            at android.os.Looper.loop(Looper.java:193)
            at android.app.ActivityThread.main(ActivityThread.java:5299)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:515)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:825)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:641)
            at dalvik.system.NativeStart.main(Native Method)

**Comment by hz3012** [comment]
Same Problem here. Using qmobile x25.

**Comment by hz3012** [comment]
https://dl.google.com/dl/android/studio/install/2.1.1.0/android-studio-bundle-143.2821654-windows.exe

**Comment by hz3012** [comment]
05-18 21:56:37.420 28317-28317/com.example.hamza.happy E/AndroidRuntime: FATAL EXCEPTION: main
                                                                         Process: com.example.hamza.happy, PID: 28317
                                                                         java.lang.NoClassDefFoundError: android.support.v7.view.menu.MenuBuilder
                                                                             at android.support.v7.app.AppCompatDelegateImplV7.initializePanelMenu(AppCompatDelegateImplV7.java:1241)
                                                                             at android.support.v7.app.AppCompatDelegateImplV7.preparePanel(AppCompatDelegateImplV7.java:1305)
                                                                             at android.support.v7.app.AppCompatDelegateImplV7.doInvalidatePanelMenu(AppCompatDelegateImplV7.java:1600)
                                                                             at android.support.v7.app.AppCompatDelegateImplV7.access$100(AppCompatDelegateImplV7.java:92)
                                                                             at android.support.v7.app.AppCompatDelegateImplV7$1.run(AppCompatDelegateImplV7.java:131)
                                                                             at android.os.Handler.handleCallback(Handler.java:808)
                                                                             at android.os.Handler.dispatchMessage(Handler.java:103)
                                                                             at android.os.Looper.loop(Looper.java:193)
                                                                             at android.app.ActivityThread.main(ActivityThread.java:5299)
                                                                             at java.lang.reflect.Method.invokeNative(Native Method)
                                                                             at java.lang.reflect.Method.invoke(Method.java:515)
                                                                             at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:825)
                                                                             at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:641)
                                                                             at dalvik.system.NativeStart.main(Native Method)
