### ISSUE TITLE
NullPointerException when fadeOut

### ISSUE THREAD

**Issue by elenaSid** [deano2390/MaterialShowcaseView#81]
Hi!
We got a lot of nullpointerexeptions: 
```
java.lang.NullPointerException
at uk.co.deanwild.materialshowcaseview.MaterialShowcaseView.notifyOnDisplayed(MaterialShowcaseView.java:208)
at uk.co.deanwild.materialshowcaseview.MaterialShowcaseView.access$1100(MaterialShowcaseView.java:42)
at uk.co.deanwild.materialshowcaseview.MaterialShowcaseView$2.onAnimationStart(MaterialShowcaseView.java:707)
at uk.co.deanwild.materialshowcaseview.AnimationFactory$1.onAnimationStart(AnimationFactory.java:29)
at android.animation.ValueAnimator.notifyStartListeners(ValueAnimator.java:903)
at android.animation.ValueAnimator.start(ValueAnimator.java:939)
at android.animation.ValueAnimator.start(ValueAnimator.java:946)
at android.animation.ObjectAnimator.start(ObjectAnimator.java:465)
at uk.co.deanwild.materialshowcaseview.AnimationFactory.fadeInView(AnimationFactory.java:44)
at uk.co.deanwild.materialshowcaseview.MaterialShowcaseView.fadeIn(MaterialShowcaseView.java:702)
at uk.co.deanwild.materialshowcaseview.MaterialShowcaseView$1.run(MaterialShowcaseView.java:671)
at android.os.Handler.handleCallback(Handler.java:733)
at android.os.Handler.dispatchMessage(Handler.java:95)
at android.os.Looper.loop(Looper.java:212)
at android.app.ActivityThread.main(ActivityThread.java:5135)
at java.lang.reflect.Method.invokeNative(Method.java)
at java.lang.reflect.Method.invoke(Method.java:515)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:877)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:693)
at dalvik.system.NativeStart.main(NativeStart.java)
```

**Comment by Ainege** [comment]
+1

**Comment by pengrad** [comment]
+1

**Comment by PollyChou** [comment]
+1
